# Generated by Django 4.1.7 on 2023-12-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowersite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, default='description'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='shopname',
            field=models.CharField(default='Default Shop', max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total',
            field=models.TextField(blank=True, default='total'),
        ),
    ]
